version: "3.7"

services:
  api:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    ports:
      - 3000

  database:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
