module.exports = {
  ERROR: {
    NOT_AUTHORIZED: 'NOT AUTHORIZED',
    RESOURCE_NOT_FOUND: 'RESOURCE NOT FOUND',
    INVALID_CREDENTIALS: 'INVALID CREDENTIALS',
    BAD_REQUEST_INPUT: 'BAD REQUEST INPUT',
    INTERNAL_SERVER_ERROR: 'INTERNAL SERVER ERROR',
    USER_REGISTERED: 'USER ALREADY REGISTERED',
    INVALID_OPERATION: 'INVALID OPERATION'
  }
}
